spring.application.name=quickcart
spring.datasource.url=jdbc:h2:mem:quickcartdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.h2.console.enabled=true
jwt.secret=TcsInternalProjectSecretKeyForQuickCart2026KeyboardSmash!